name: Mineplex Studio Map Rotation Action
run-name: Rotate Maps
on:
  workflow_dispatch:
    inputs:
      count:
        type: number
        required: true
        description: Number of maps to swap in active pool
jobs:
  swap-maps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure map-rotation.sh is executable
      run: chmod +x ./scripts/map-rotation.sh

    - name: Run the bash script
      id: swap_maps
      run: ./scripts/map-rotation.sh ${{ inputs.count }}
